name: Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
      - name: Use Python ${{ matrix.node-version }}
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - name: GCloud auth
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.BIGQUERY_KEY }}'
      - name: Install and test
        run: |
          python3 -m pip install --upgrade pip --user
          python3 -m pip install pip-tools --user
          python3 -m pip install -r requirements.dev.txt --user
          python3 -m pip install -e . --user
          python3 -m pylint src tests
          python3 -m yapf --diff --recursive src tests
          ./scripts/gen-services.sh
          ./scripts/gen-snowflake-auth.sh
          python3 -m pytest --junitxml=junit/test-results.xml -rxXs
        env:
          CI: true
          SNOWFLAKE_CONNECTION: ${{ secrets.SNOWFLAKE_CONNECTION }}
